### ISSUE TITLE
Hidden content when `@media screen` should be visible and accessible for `@media print`

### ISSUE THREAD

**Issue by smillart** [smillart/WAI-ARIA-Patterns-And-Widgets#16]
The **printable version** should contain/display all the `main` page contents that are not rendered by default to the users. Therefore, all section of `[hidden]` content (`@media screen`) should be visible and accessible when printed (`@media print`) on a sheet of paper, to a PDF file, ...

The following CSS rules have to be added to both the **Minimum required styles** `[./dist/css/aria-required.min.css]` and the **CSS transition styles** `[./dist/css/aria-transition.min.css]` for the WAI-ARIA widgets:

```css
@media print {
  [class*='aria-'][hidden] {
    display: block;
  }
  [class*='aria-'][class*='--transition'][hidden] {
    max-height: 80vh;
    padding-top: 1rem;
    padding-bottom: 1rem;
    visibility: visible;
    opacity: 1;
  }
}
```
